### ISSUE TITLE
Error running make (ubuntu 16.04)

### ISSUE THREAD

**Issue by dragonware-com** [pulp-platform/ri5cy_gnu_toolchain#27]
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/home/wsun/ri5cy_gnu_toolchain/build/src/binutils/bfd -I. -I/home/wsun/ri5cy_gnu_toolchain/build/src/binutils/bfd -I/home/wsun/ri5cy_gnu_toolchain/build/src/binutils/bfd/../include -DHAVE_riscv_elf32_vec -DHAVE_elf32_le_vec -DHAVE_elf32_be_vec -DHAVE_plugin_vec -DBINDIR=\"/home/wsun/ri5cy_gnu_toolchain/install/bin\" -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -g -O2 -MT elf32-riscv.lo -MD -MP -MF .deps/elf32-riscv.Tpo -c elf32-riscv.c -o elf32-riscv.o
/home/wsun/ri5cy_gnu_toolchain/build/src/binutils/bfd/elfxx-riscv.c:26:17: fatal error: bfd.h: No such file or directory
compilation terminated.
Makefile:1607: recipe for target 'elfxx-riscv.lo' failed
make[5]: *** [elfxx-riscv.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
/home/wsun/ri5cy_gnu_toolchain/build/src/binutils/bfd/elfnn-riscv.c:28:17: fatal error: bfd.h: No such file or directory
compilation terminated.

**Comment by dragonware-com** [comment]
Can someone post a working environment (OS, package, host compiler version) that can make this work?

**Comment by mbolivar** [comment]
I'm also seeing an error when trying build on ubuntu 18.04. @dragonware-com did you find anything?

```
In file included from /home/mbolivar/src/ri5cy_gnu_toolchain/build/src/newlib-gcc/gcc/cp/except.c:1023:0:
cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
Makefile:1064: recipe for target 'cp/except.o' failed
```

**Comment by rockman182** [comment]
I have the same problem on ubuntu 18.04.
After change to use gcc/gcc++ 5.5.0 , everything is okay.

**Comment by suhasskrishanmurthy** [comment]
@rockman182 what do you mean by changing gcc/gcc++ 5.5.0 ...  I also have the same problem

**Comment by rockman182** [comment]
@suhasskrishanmurthy ubuntu 18.04 build in gcc is 7.x.x , you need to install an older gcc version.
https://askubuntu.com/questions/1087150/install-gcc-5-on-ubuntu-18-04
